name: Checks
on:
  [pull_request]

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.go-version}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        os-version: ['stable']
        go-version: ['1.18', '1.19', '1.20', '1.21', '1.22']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true
      - name: Run tests
        run: go test ./...
      
